"""rename product metadata to raw_metadata and add missing columns

Revision ID: 231c003551e3
Revises: 438c7550afd8
Create Date: 2026-02-24 19:12:40.593192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '231c003551e3'
down_revision: Union[str, Sequence[str], None] = '438c7550afd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_tree', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('product', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('product', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('product', sa.Column('financing_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('product', sa.Column('discovered_from', sa.String(length=2048), nullable=True))
    op.add_column('product', sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('product', sa.Column('review_count', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('badges', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('product', sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'raw_metadata')
    op.drop_column('product', 'badges')
    op.drop_column('product', 'review_count')
    op.drop_column('product', 'rating_avg')
    op.drop_column('product', 'discovered_from')
    op.drop_column('product', 'financing_options')
    op.drop_column('product', 'images')
    op.drop_column('product', 'description')
    op.drop_column('product', 'category_tree')
    # ### end Alembic commands ###
