"""add_ux_fields

Revision ID: 2fe5cdc17306
Revises: dbf8d148b238
Create Date: 2026-02-24 03:31:30.504922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe5cdc17306'
down_revision: Union[str, Sequence[str], None] = 'dbf8d148b238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletter_message', sa.Column('body_preview', sa.Text(), nullable=True))
    op.add_column('newsletter_message', sa.Column('body_html', sa.Text(), nullable=True))
    op.add_column('page_snapshot', sa.Column('screenshot_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_snapshot', 'screenshot_url')
    op.drop_column('newsletter_message', 'body_html')
    op.drop_column('newsletter_message', 'body_preview')
    # ### end Alembic commands ###
