"""initial_schema_all_tables

Revision ID: 95cff26e2644
Revises: 
Create Date: 2026-02-24 01:50:15.831999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95cff26e2644'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('vertical', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('PENDING_ONBOARDING', 'ACTIVE', 'PAUSED', 'ERROR', name='competitorstatus'), nullable=False),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('crawl_run',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED_PARTIAL', 'FAILED', name='jobstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_brief',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('brief_date', sa.Date(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='briefstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brief_date')
    )
    op.create_table('job_execution_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED_PARTIAL', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newsletter_account',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('imap_host', sa.String(length=255), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('mailbox_config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('signal_taxonomy',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('PROMO', 'FINANCIACION', 'ENVIO', 'URGENCIA', 'CTA', 'BRAND_HIGHLIGHT', name='signaltype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subscription_tier',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('max_competitors', sa.Integer(), nullable=False),
    sa.Column('max_monitored_pages', sa.Integer(), nullable=False),
    sa.Column('monitoring_frequency', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='monitoringfrequency'), nullable=False),
    sa.Column('history_retention_days', sa.Integer(), nullable=False),
    sa.Column('can_track_newsletters', sa.Boolean(), nullable=False),
    sa.Column('can_track_tech_stack', sa.Boolean(), nullable=False),
    sa.Column('can_track_catalog', sa.Boolean(), nullable=False),
    sa.Column('can_use_realtime_alerts', sa.Boolean(), nullable=False),
    sa.Column('can_access_api', sa.Boolean(), nullable=False),
    sa.Column('can_generate_weekly_brief', sa.Boolean(), nullable=False),
    sa.Column('can_use_baseline_comparison', sa.Boolean(), nullable=False),
    sa.Column('price_monthly_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('weekly_brief',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Enum('NEW_PROMO', 'REMOVED_PROMO', 'CHANGED_HERO', 'CHANGED_FINANCING', 'FLASH_SALE', name='eventtype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('tier_id', sa.BigInteger(), nullable=True),
    sa.Column('billing_status', sa.Enum('TRIAL', 'ACTIVE', 'PAST_DUE', 'CANCELLED', name='billingstatus'), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tier_id'], ['subscription_tier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('competitor_tech_profile',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.BigInteger(), nullable=False),
    sa.Column('ecommerce_platform', sa.String(length=100), nullable=True),
    sa.Column('platform_version', sa.String(length=100), nullable=True),
    sa.Column('analytics_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('marketing_automation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tag_managers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payment_gateways', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('live_chat', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cdn_provider', sa.String(length=100), nullable=True),
    sa.Column('js_frameworks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('full_fingerprint_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('last_fingerprinted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competitor_id')
    )
    op.create_table('monitored_page',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('page_type', sa.Enum('HOMEPAGE', 'PROMO_PAGE', 'FINANCING_PAGE', 'SHIPPING_PAGE', 'CATEGORY', 'OTHER', name='pagetype'), nullable=False),
    sa.Column('discovery_method', sa.Enum('AUTO', 'MANUAL', name='discoverymethod'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newsletter_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.BigInteger(), nullable=False),
    sa.Column('newsletter_account_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=1024), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_html_path', sa.String(length=1024), nullable=True),
    sa.Column('is_optin_confirmation', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ),
    sa.ForeignKeyConstraint(['newsletter_account_id'], ['newsletter_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newsletter_subscription',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.BigInteger(), nullable=False),
    sa.Column('newsletter_account_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_AUTO', 'PENDING_OPTIN', 'PENDING_MANUAL', 'ACTIVE', 'FAILED', name='newsletterstatus'), nullable=False),
    sa.Column('auto_sub_attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ),
    sa.ForeignKeyConstraint(['newsletter_account_id'], ['newsletter_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.BigInteger(), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('category_path', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tech_profile_change',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.BigInteger(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('change_type', sa.Enum('ADDED', 'REMOVED', 'CHANGED', name='techchangetype'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tech_profile_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('ecommerce_platform', sa.String(length=100), nullable=True),
    sa.Column('full_fingerprint_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_competitor',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('competitor_id', sa.BigInteger(), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority'), nullable=False),
    sa.Column('history_access_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'competitor_id', name='uq_client_competitor')
    )
    op.create_table('page_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('monitored_page_id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_storage_path', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('PENDING_EXTRACTION', 'EXTRACTED', 'ERROR', name='snapshotstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitored_page_id'], ['monitored_page.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['crawl_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upsell_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('competitor_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Enum('HISTORICAL_DATA_AVAILABLE', 'TIER_UPGRADE_SUGGESTED', name='upselleventtype'), nullable=False),
    sa.Column('data_available_since', sa.Date(), nullable=True),
    sa.Column('snapshots_count', sa.Integer(), nullable=False),
    sa.Column('signals_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OFFERED', 'ACCEPTED', 'DECLINED', name='upsellstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detected_signal',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.Enum('WEB', 'EMAIL', name='signalsource'), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('taxonomy_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_text_found', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['page_snapshot.id'], ),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['signal_taxonomy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('list_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_in_stock', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['page_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    op.drop_table('detected_signal')
    op.drop_table('upsell_event')
    op.drop_table('page_snapshot')
    op.drop_table('client_competitor')
    op.drop_table('tech_profile_history')
    op.drop_table('tech_profile_change')
    op.drop_table('product')
    op.drop_table('newsletter_subscription')
    op.drop_table('newsletter_message')
    op.drop_table('monitored_page')
    op.drop_table('competitor_tech_profile')
    op.drop_table('client')
    op.drop_table('change_event')
    op.drop_table('weekly_brief')
    op.drop_table('subscription_tier')
    op.drop_table('signal_taxonomy')
    op.drop_table('newsletter_account')
    op.drop_table('job_execution_log')
    op.drop_table('daily_brief')
    op.drop_table('crawl_run')
    op.drop_table('competitor')
    # ### end Alembic commands ###
